language: generic
services:
  - docker

before_install:
  - docker build -t chandanjainn/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chandanjainn/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-poc"
  env: "Dockerpoc-env"
  bucket_name: "elasticbeanstalk-ap-south-1-921749941109"
  bucket_path: "docker-poc"
  on:
    branch: release
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
